---
-
  name: "Check Connectivity to target servers"
  hosts: target2
  remote_user: root
  become: yes
  tasks:
    -
      name: "Ping Test"
      ping:
    -
      name: 'Execute a command to display hosts file'
      command: 'cat /etc/hosts'
      register: hosts
    -
      debug:
        var: hosts.stdout_lines
    -
      name: Install python3
      dnf: pkg=python3 state=latest
#updated file
