---
-
  name: "Check Connectivity to target servers"
  hosts: target2
  remote_user: centos
  become: yes
  tasks:
    -
      name: "Ping Test"
      ping:
    -
      name: 'Execute a command to display hosts file'
      command: 'cat /etc/hosts'
      register: hosts
    -
      debug:
        var: hosts.stdout_lines
    -
      name: download files
      sudo: yes
      action: wget -c https://atom.io/download/rpm -O atom.rpm
    -
      name: Install atom
      sudo: yes
      action: rpm -i atom.rpm
#updated file
